name: Deploy to AWS
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          version: 10.x
      - name: Build
        env:
          REACT_APP_GRAPHQL_SERVER_URI: ${{ secrets.REACT_APP_GRAPHQL_SERVER_URI }}
        run: |
          yarn
          yarn build --if-present
      - name: Deploy to S3
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          AWS_DEFAULT_REGION: "ap-southeast-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
        run: node scripts/deploy.js
      - name: Invalidate Cloudfront CDN
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: "/index.html"
          AWS_REGION: "ap-southeast-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
